/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface MyComponentAttributes extends StencilHTMLAttributes {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }

  interface TheHeader {}
  interface TheHeaderAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'MyComponent': Components.MyComponent;
    'TheHeader': Components.TheHeader;
  }

  interface StencilIntrinsicElements {
    'my-component': Components.MyComponentAttributes;
    'the-header': Components.TheHeaderAttributes;
  }


  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLTheHeaderElement extends Components.TheHeader, HTMLStencilElement {}
  var HTMLTheHeaderElement: {
    prototype: HTMLTheHeaderElement;
    new (): HTMLTheHeaderElement;
  };

  interface HTMLElementTagNameMap {
    'my-component': HTMLMyComponentElement
    'the-header': HTMLTheHeaderElement
  }

  interface ElementTagNameMap {
    'my-component': HTMLMyComponentElement;
    'the-header': HTMLTheHeaderElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
